export const demoUser = {
  id: 'demo-user',
  name: 'Demo Applicant',
  email: '',
  phone: '',
  location: 'Pakistan',
  preferences: {
    roles: ['Software Engineer', 'Backend Engineer', 'Data Analyst'],
    locations: ['Remote', 'Lahore', 'Islamabad', 'Karachi'],
    jobTypes: ['Remote', 'Office 9-5', 'Internship', 'Hybrid'],
    minSalary: 0,
    experienceLevel: 'Entry to Mid',
    dailySendLimit: 15,
    blacklist: [],
  },
}

export const seedJobs = [
  {
    id: 'seed-remote-backend-arbisoft',
    title: 'Backend Engineer (Node.js)',
    company: 'Arbisoft',
    location: 'Remote',
    type: 'Remote',
    salary: '$2k-$4k/month',
    salaryMin: 2000,
    source: 'Demo Board',
    posted: 'Today',
    url: 'https://example.com/jobs/backend-engineer',
    recruiterEmail: 'careers@example.com',
    recruiterPhone: '+923001234567',
    description: 'Build Node.js APIs, PostgreSQL services, background workers, and cloud integrations for international SaaS clients.',
    tags: ['Node.js', 'PostgreSQL', 'AWS', 'REST APIs', 'JavaScript'],
  },
  {
    id: 'seed-office-db-systems',
    title: 'Database Engineer',
    company: 'Systems Ltd',
    location: 'Lahore, Pakistan',
    type: 'Office 9-5',
    salary: 'PKR 140k-220k',
    salaryMin: 140000,
    source: 'Demo Board',
    posted: 'Today',
    url: 'https://example.com/jobs/database-engineer',
    recruiterEmail: 'hr@example.com',
    recruiterPhone: '+923111234567',
    description: 'Design PostgreSQL schemas, optimize queries, build reporting pipelines, and support data reliability for business systems.',
    tags: ['PostgreSQL', 'SQL', 'Data Modeling', 'Redis', 'ETL'],
  },
  {
    id: 'seed-intern-ml-giki',
    title: 'Machine Learning Intern',
    company: 'GIKI Tech Incubator',
    location: 'Islamabad, Pakistan',
    type: 'Internship',
    salary: 'PKR 25k-40k',
    salaryMin: 25000,
    source: 'Demo Board',
    posted: 'Yesterday',
    url: 'https://example.com/jobs/ml-intern',
    recruiterEmail: 'internships@example.com',
    recruiterPhone: '+923221234567',
    description: 'Assist with Python data cleaning, scikit-learn experiments, dashboards, model evaluation, and research prototypes.',
    tags: ['Python', 'Pandas', 'scikit-learn', 'Data Science', 'Jupyter'],
  },
  {
    id: 'seed-hybrid-fullstack-netsol',
    title: 'Full Stack Developer',
    company: 'Netsol Technologies',
    location: 'Lahore / Remote',
    type: 'Hybrid',
    salary: 'PKR 180k-280k',
    salaryMin: 180000,
    source: 'Demo Board',
    posted: '2 days ago',
    url: 'https://example.com/jobs/full-stack',
    recruiterEmail: 'talent@example.com',
    recruiterPhone: '+923331234567',
    description: 'Ship React interfaces, Node.js APIs, authentication flows, relational database features, and production fixes.',
    tags: ['React', 'Node.js', 'MySQL', 'Authentication', 'TypeScript'],
  },
  {
    id: 'seed-remote-data-i2c',
    title: 'Data Analyst',
    company: 'i2c Inc',
    location: 'Remote',
    type: 'Remote',
    salary: '$1.5k-$3k/month',
    salaryMin: 1500,
    source: 'Demo Board',
    posted: '3 days ago',
    url: 'https://example.com/jobs/data-analyst',
    recruiterEmail: 'recruiting@example.com',
    recruiterPhone: '+923441234567',
    description: 'Create SQL dashboards, analyze product metrics, prepare stakeholder reports, and automate recurring analysis.',
    tags: ['SQL', 'Python', 'Power BI', 'Excel', 'Analytics'],
  },
  {
    id: 'seed-office-junior-tkxel',
    title: 'Junior Software Engineer',
    company: 'Tkxel',
    location: 'Lahore, Pakistan',
    type: 'Office 9-5',
    salary: 'PKR 90k-140k',
    salaryMin: 90000,
    source: 'Demo Board',
    posted: 'This week',
    url: 'https://example.com/jobs/junior-software-engineer',
    recruiterEmail: 'jobs@example.com',
    recruiterPhone: '+923551234567',
    description: 'Work with JavaScript, React, REST APIs, Git, bug fixes, and agile delivery for client software projects.',
    tags: ['JavaScript', 'React', 'REST APIs', 'Git', 'HTML'],
  },
]
